
services:
  viajes_dashboard_db:
    container_name: viajes_dashboard_db
    image: postgres:16.10-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - viajes_dashboard_db:/var/lib/postgresql/data

volumes:
  viajes_dashboard_db:
    driver: local
